#!/bin/bash

readonly dockerfile=${1}
readonly imagetag=${2}

env

echo "Image tag ${imagetag}"
echo "Patching user id to ${CUSTOM_USER_ID} in ${dockerfile}"

sed -i "s/_UID_/${CUSTOM_USER_ID}/g" "${dockerfile}"
